### ISSUE TITLE
jms/serializer problem (response to issue #148)

### ISSUE THREAD

**Issue by KalebClark** [AuthorizeNet/sdk-php#151]
Thanks for taking a look at this. I have added the following authorize.net package:

    "authorizenet/authorizenet": "dev-master#d63a785803647e4d137a56cecb7c150e15c32fef",
And now I am getting the following message:

Problem 1
- Installation request for authorizenet/authorizenet dev-master#d63a785803647e4d137a56cecb7c150e15c32fef -> satisfiable by authorizenet/authorizenet[dev-master].

- authorizenet/authorizenet dev-master requires jms/serializer serializer-master-dev as 1.0 -> no matching package found.

I have tried many different versions of serializer, and left it out to let this package install, but no luck any way.

Any ideas?

Thanks again,
-Kaleb Clark

**Comment by jdavidbakr** [comment]
Getting this same error trying to download version 1.8.9 (when specifying "^1.8" composer is rolling all the way back to 1.8.0)  It appears that 1.8.4 is the first version with this issue, I had to specify "^1.8.3.3" to avoid this error.

**Comment by brianmc** [comment]
Apologies, we had an out of date readme with incorrect composer section.  We have updated the readme https://github.com/AuthorizeNet/sdk-php  you can also see a sample composer.json on our sample code repo here:  https://github.com/AuthorizeNet/sample-code-php/blob/master/composer.json   This repo has CI enabled so it should be run for correctness every night.

Thanks for the feedback and appreciate the patience as we try to streamline the dependency chain.

Brian

**Comment by jdavidbakr** [comment]
Thanks @brianmc for your response, I'm finally going back in and trying to update to 1.8.9 (or 1.9.0) but even following those instructions I'm still getting an error:

```
  Problem 1
    - The requested package jms/serializer serializer-master-dev as 1.0 exists as jms/serializer[0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, dev-master, 1.3.x-dev, dev-mowcixo-master] but these are rejected by your constraint.
  Problem 2
    - Installation request for authorizenet/authorizenet 1.8.9 -> satisfiable by authorizenet/authorizenet[1.8.9].
    - authorizenet/authorizenet 1.8.9 requires jms/serializer serializer-master-dev as 1.0 -> no matching package found.
```

I can remove Problem 1 by changing my composer serializer to look for "dev-master as 1.0" but Problem 2 remains because that's how the composer.json file references it in the authorize.net composer.json file.

**Comment by ashtru** [comment]
@jdavidbakr, are you using a composer.json with contents similar to that of sample-code-php [composer](https://github.com/AuthorizeNet/sample-code-php/blob/master/composer.json)  I find it more concise than using the composer for sdk-php.If not, can you try and please share the output/errors?

**Comment by jdavidbakr** [comment]
@ashtru doh, you can close this issue, I misspelled 'repositories' in my composer.json file.

**Comment by ashtru** [comment]
Glad to hear that @jdavidbakr.
